name: Deploy Redis to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Produccion
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Terraform Init
        if: ${{ endsWith(github.workspace, '.tf') }}
        uses: hashicorp/terraform-github-actions@v0.12.0
        with:
          tf_command: "init"
          working_directory: ./infra

      - name: Terraform Apply
        if: ${{ endsWith(github.workspace, '.tf') }}
        uses: hashicorp/terraform-github-actions@v0.12.0
        with:
          tf_command: "apply"
          working_directory: ./infra
          args: "-auto-approve"

      - name: Azure Logout
        run: az logout
